# Header

menu:
  主页: /
  前端: /categories/web
  随笔: /categories/essays/
  相册: photo

# SubNav
subnav:
  github: "https://github.com/huyongdi"
  weibo: "http://weibo.com/huyongdi/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1"
  zhihu: "https://www.zhihu.com/people/hu-yong-di-33"
  #mail: "354224080@qq.com"
  #qq: "链接地址"
  #rss: "#"
  #douban: "#"
  #mail: "354224080@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content
excerpt_link: more
fancybox: true
mathjax: false
# show_all_link: false
# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
google_analytics: ''
favicon: /assets/img/favicon.ico

#你的头像url

avatar: http://7xt475.com1.z0.glb.clouddn.com/QQ%E5%9B%BE%E7%89%8720170303144525.jpg

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论

duoshuo: "huyongdi"

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#009933'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false


# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: false
  friends: false
  aboutme: '关于我'


friends:

  友情链接1: 暂定
  友情链接2: 暂定
  友情链接3: 暂定
  友情链接4: 暂定
  友情链接5: 暂定
  友情链接6: 暂定

aboutme: 用来记录<br><br>部分生活和前端知识
